import React from "react";
import { View, StyleSheet, ScrollView, Pressable } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useHeaderHeight } from "@react-navigation/elements";
import { Feather } from "@expo/vector-icons";
import * as WebBrowser from "expo-web-browser";
import Animated, { FadeInDown } from "react-native-reanimated";

import { ThemedText } from "@/components/ThemedText";
import { ThemedView } from "@/components/ThemedView";
import { useTheme } from "@/hooks/useTheme";
import { Spacing, BorderRadius } from "@/constants/theme";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "@/navigation/RootStackNavigator";

type Props = NativeStackScreenProps<RootStackParamList, "PrivacyPolicy">;

export default function PrivacyPolicyScreen({ navigation }: Props) {
  const { theme } = useTheme();
  const insets = useSafeAreaInsets();
  const headerHeight = useHeaderHeight();

  const handleOpenFull = () => {
    WebBrowser.openBrowserAsync("https://skaisay.github.io/App-Privacy/");
  };

  const sections = [
    {
      title: "Terms of Use (EULA)",
      content: "Last updated: January 2026\n\nBy using the Moments app, you agree to the Apple Standard License Agreement (EULA): https://www.apple.com/legal/internet-services/itunes/dev/stdeula/\n\nThe app is intended for users over 18 years old.\n\nProhibited:\n• Posting illegal, offensive, or inappropriate content\n• Insults, threats, discrimination against other users\n• Spam, fraud, distribution of malware\n• Violation of copyrights and intellectual property\n\nWe reserve the right to remove content and block users without warning for rule violations. Reports are processed within 24 hours."
    },
    {
      title: "Privacy Policy",
      content: "This app is designed with user privacy as a priority. It does not require providing personal information such as real name, email address, phone number, or identity documents."
    },
    {
      title: "User Accounts",
      content: "The app uses a simplified account system. No email, phone number, real name, or profile photo is required. User profiles can only use emoji-based avatars. Each user is identified by a unique internal ID generated by the system."
    },
    {
      title: "Permissions",
      content: "The app may request access to the following device features solely to provide core functionality:\n\n• Camera – for users to take photos and videos for posting.\n• Photo Gallery – for users to select and upload existing photos or videos.\n• Location (geolocation) – to optionally attach location information to content.\n\nAccess to these features is requested only when necessary and is not used for tracking or advertising."
    },
    {
      title: "Stored Content",
      content: "The app stores user content such as messages, photos, videos, comments, likes, and associated metadata. This data is stored on servers solely to ensure the operation of the app's features."
    },
    {
      title: "Content Moderation",
      content: "We apply filtering for objectionable content. Users can report inappropriate content or block other users. Developers process reports within 24 hours, removing violating content and blocking violators."
    },
    {
      title: "No Ads or Tracking",
      content: "There are no ads in the app, and it does not use third-party analytics, tracking technologies, or advertising SDKs. User data is not shared with third parties."
    },
    {
      title: "Contacts",
      content: "For any questions, please contact:\nEmail: messaconfirmation@gmail.com\nDiscord: https://discord.gg/FRAZ6PBcH9\n\nWe respond within 24 hours."
    }
  ];

  return (
    <ThemedView style={styles.container}>
      <View style={[styles.header, { paddingTop: insets.top + Spacing.sm }]}>
        <Pressable onPress={() => navigation.goBack()} hitSlop={8}>
          <Feather name="x" size={24} color={theme.text} />
        </Pressable>
        <ThemedText type="h3">Privacy</ThemedText>
        <View style={{ width: 24 }} />
      </View>
      <ScrollView
        contentContainerStyle={{
          paddingTop: Spacing.sm,
          paddingBottom: insets.bottom + Spacing["2xl"],
          paddingHorizontal: Spacing.lg,
        }}
        showsVerticalScrollIndicator={false}
      >
        {sections.map((section, index) => (
          <Animated.View 
            key={index} 
            entering={FadeInDown.delay(index * 100)}
            style={styles.section}
          >
            <ThemedText type="h4" style={styles.sectionTitle}>
              {section.title}
            </ThemedText>
            <ThemedText type="body" style={[styles.sectionContent, { color: theme.textSecondary }]}>
              {section.content}
            </ThemedText>
          </Animated.View>
        ))}

        <Animated.View entering={FadeInDown.delay(900)} style={styles.footer}>
          <Pressable 
            onPress={handleOpenFull}
            style={[styles.linkButton, { backgroundColor: theme.backgroundSecondary }]}
          >
            <ThemedText type="body" style={{ color: theme.link, fontWeight: "600" }}>
              Read full version on website
            </ThemedText>
            <Feather name="external-link" size={16} color={theme.link} style={{ marginLeft: Spacing.xs }} />
          </Pressable>
        </Animated.View>
      </ScrollView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.md,
  },
  section: {
    marginBottom: Spacing.xl,
  },
  sectionTitle: {
    marginBottom: Spacing.sm,
  },
  sectionContent: {
    lineHeight: 22,
  },
  footer: {
    marginTop: Spacing.xl,
    alignItems: "center",
  },
  linkButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xl,
    borderRadius: BorderRadius.full,
  },
});
